### ISSUE TITLE
replaceEnabled does not change to second alert when change is too quick

### ISSUE THREAD

**Issue by jseils107** [testshallpass/react-native-dropdownalert#215] opened 2019-10-15 16:35 UTC
#### Short Description

When calling multiple 'alertWithType' within ~500 milliseconds of each other, the second alert does not generate.  For example, I am calling an alert on a request of 'pending' and when that request is fulfilled it should replace with a 'success' or 'error' alert type.

However, when that request is fulfilled extremely quickly the second alert will not replace the initial alert.  I have tried with replaceEnabled as both true and false.  Neither works every time.

I am using Redux and calling alertWithType from the redux action.  I know there was a decision to not include queues, however I feel like a queue would solve this issue.

#### Steps to Reproduce / Code Snippets / Usage

DropDownHolder.dropDown.alertWithType('info', 'Processing', 'Processing Request...')

setTimeout(function(){
                DropDownHolder.dropDown.alertWithType('success', 'Success!', 'Request Processed Successfully')
}, 100)

#### Expected Results

I would expect that the processing alert would be replaced by the success alert once the response is received. However, the processing alert will remain in the foreground and the second alert will not show up.  

### Additional Information

* React Native version: 0.59
* react-native-dropdownalert version: 4.2.0
* Platform(s) (iOS, Android, or both?): iOS
* iOS version: 13.1.2
* Android version: n/a

**Comment by sebinq** [comment] 2019-11-18 11:49
same here.

**Comment by testshallpass** [comment] 2020-05-20 18:46
I investigated and can reproduce it with steps described. The problem is the animation lock is enabled by default and blocks the second invocation of `alertWithType`. A workaround is to disable it, however after I retest it may not be what's desired. I'm experimenting with suggested queue processing.

**Comment by testshallpass** [comment] 2020-05-21 01:45
The experiment was successful and it really works great. I think it will also be useful as well where there is a need to inform user of steps to a process in a series of alerts. PR #224

**Comment by testshallpass** [comment] 2020-07-13 02:40
Closing as alert queue has been published. See v4.3.0.

**Closed by testshallpass** 2020-07-13 02:40 UTC
Labels: enhancement
