### ISSUE TITLE
DropDown Alert is not automatically closing after the closeInterval time

### ISSUE THREAD

**Issue by kcfgl** [testshallpass/react-native-dropdownalert#76] opened 2017-08-07 21:07 UTC
#### Issue Description

Even with closeInterval set to {2000} the dropdown will not close on its own. Tapping the dropdown will close it, and when I inspect the console, it shows 'automatic' as the action.

#### Steps to Reproduce / Code Snippets

Add the DropDown alert
```
<DropdownAlert
            ref={(ref) => this.dropdown = ref}
            closeInterval={2000}
            titleStyle={styles.alertTitle}
            messageStyle={styles.alertMessage}
            errorColor={RED_ALERT_COLOR}
            onClose={(data) => this.onClose(data)}  />
```
After an error is thrown in my code, trigger the Dropdown

`this.dropdown.alertWithType('error', 'NOT AVAILABLE', 'Sorry, but that time is not available');`
     
The DropDownAlert should show on the screen and then hide itself after 2 seconds.  What actually happens is the alert shows on the screen and then remains.  Tapping it or swiping it will dismiss it.

#### Expected Results

The DropDown appears on the screen and then after the time set in closeInterval, the DropDownAlert will hide itself.

### Additional Information

* React Native version: 0.45.1
* react-native-dropdownalert version: ^2.10.0
* Platform(s) (iOS, Android, or both?): iOS

This is an excellent library BTW. Thank you for building it.

**Comment by kcfgl** [comment] 2017-08-08 01:46
Weird, but I forked this to try to look into the issue, and now this is not happening.  I'll keep checking into it but will close this for now.

**Comment by kcfgl** [comment] 2017-08-14 09:29
After a bit more work, it looks like the dropdown won't automatically close on views where I have input fields. I'll dig in a bit to see if I can determine why that is.

**Steps to reproduce:** 

1. Add a dropdown to a view with a TextInput
2. Trigger the dropdown to show and tapToClose=false and closeInterval=3000
3. The dropdown will not hide
4. Tap in any TextInput and the dropdown will hide

**Comment by testshallpass** [comment] 2017-08-20 04:22
Hi @kcfgl Strange. Yeah it should not matter if you have both props. I am skeptical that it's the TextInput. What else do you have on the view? What action invokes the alert?

**Comment by kcfgl** [comment] 2017-08-20 13:33
@testshallpass You're right. I have a dropdown on about a dozen views, almost all of which have a TextInput. BUT there is one that doesn't and I confirmed that it is not closing automatically there either. So here's what I've got. 

Dropdown
 ```
            <DropdownAlert
                ref={(ref) => this.dropdown = ref}
                titleStyle={styles.alertTitle}
                messageStyle={styles.alertMessage}
                containerStyle={{justifyContent: 'center'}}
                errorColor={RED_ALERT_COLOR}
                successColor={GOLD_COLOR}
                closeInterval={3000}
                tapToCloseEnabled={false}
                updateStatusBar={false}
             />
```
Trigger dropdown 
`this.dropdown.alertWithType('error', 'SOMETHING WENT WRONG', 'It is probably on our end. Give it a try again.');`

I've attempted to call this from multiple places.  Most often it is something like: 
```
firebase.database().ref().update(updates)
    .then((success) => {
        console.log('success saving the slip request');
        this.dropdown.alertWithType('success', 'SUCCESS', 'All good here. Carry on..');
    })
    .catch((error) => {
        console.log(" failure: ",error);
        // Show error
        this.dropdown.alertWithType('error', 'SOMETHING WENT WRONG', 'It is probably on our end. Give it a try again.');
    });
```
I've also attempted to put this.dropdown.alertWithType in its own function and call that, just to see if it made a difference. 

Last note. On the view referenced above. The dropdown shows up and stays. There is a button on the view and if I tap the button the dropdown will hide. If I navigate back or forward the dropdown will hide. 

So I'm a bit at a loss here. Especially since it has actually worked for me in the past.  And I love this component so I'm determined to figure out what I've done wrong.  Thanks for your help.

**Comment by testshallpass** [comment] 2017-09-30 02:57
@kcfgl Sorry for late response. I'm kinda baffled too. Try removing most of the props like closeInterval. If all else is failing you could close yourself by invoking `this.dropdown.close()` on your own timeout, not really too helpful but might be worth the try as a workaround. I will try to setup a sandbox to debug this more, if it still persists.

**Comment by projetedt** [comment] 2017-10-16 12:08
There is any news about that bug ? We are dealing with this problem too.

**Comment by kcfgl** [comment] 2017-10-16 12:16
I’m actually still seeing this ... but without any real pattern. Most of the time however, it’s totally fine now. Truly bizarre. I moved away from worrying about it and onto other areas of the product, but I’m actially coming back to it now before shipping. I’m going to try @holyxiaoxin suggestion and see what I see.

**Comment by koswarabilly** [comment] 2017-11-15 09:42
it has been 29  days , have it been fixed?

**Comment by testshallpass** [comment] 2017-11-25 05:44
Closing since I don't see myself fixing this and the nature of the issue has no "real pattern" to reproduce.

**Closed by testshallpass** 2017-11-25 05:44 UTC
Labels: bug, help wanted, ios

**Comment by jayeshjain24** [comment] 2018-01-29 14:29
My error is exactly opposite. The dropdown is autoclosing quickly and closeInterval does not have any effect on it.
