### ISSUE TITLE
Dropdownalert is jumping

### ISSUE THREAD

**Issue by AndriiBoiko** [testshallpass/react-native-dropdownalert#223] opened 2020-03-20 12:41 UTC
Sometimes we can see strange behaviour 
Dropdownalert is jumping
Implementation
```
const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
});
```
```
      <View style={styles.container}>
        <Provider store={store}>
          <PersistGate loading={<PersistLoading />} persistor={persistor}>
            <AppContainer ref={navigatorRef => NavigationService.setTopLevelNavigator(navigatorRef)} />
            <ModalContainer />
          </PersistGate>
        </Provider>
        <DropdownAlert
          updateStatusBar={false}
          ref={ref => AlertHelper.setDropDown(ref)}
          onClose={() => AlertHelper.invokeOnClose()}
          closeInterval={3200}
        />
      </View>
```

### Additional Information

* React Native version: 0.59.9
* react-native-dropdownalert version: ^4.2.1
* Platform(s) (iOS, Android, or both?): IOS
* iOS version: 13.3

#### Pls take a look for screenshots:
step by step
1 -> 2 -> 3
<img width="498" alt="1" src="https://user-images.githubusercontent.com/50368724/77164117-42796480-6ab8-11ea-98ab-25267a899182.png">
<img width="498" alt="2" src="https://user-images.githubusercontent.com/50368724/77164130-47d6af00-6ab8-11ea-8bf0-147fc9b5433a.png">
<img width="498" alt="3" src="https://user-images.githubusercontent.com/50368724/77164149-52914400-6ab8-11ea-9eec-6668311570e4.png">

#### I also added gif - it might be more informative

![jump mov](https://user-images.githubusercontent.com/50368724/77164235-81a7b580-6ab8-11ea-8329-b6bf4b5f72c9.gif)

**Comment by testshallpass** [comment] 2020-05-21 02:13
The cause and this hunch is that one alert is competing with another alert. Each time alert is invoked by `alertWithType` it tries to close preexisting one and open brand new one. I think it will be solved with queue implementation. PR #224 and tagging this as related to #215

**Comment by testshallpass** [comment] 2020-07-13 02:42
Closing, try out the new alert queue in v4.3.0.

**Closed by testshallpass** 2020-07-13 02:42 UTC
Labels: ios, needs investigation
