### ISSUE TITLE
PNGs cause release build problem with Android

### ISSUE THREAD

**Issue by dominicrico** [testshallpass/react-native-dropdownalert#130] opened 2018-04-23 13:03 UTC
#### Short Description

Gradle Build fails, because of image sources.
Gradle Log:
```
:app:processReleaseResources
/XXX/RNApp/android/app/build/intermediates/res/merged/release/drawable-xhdpi/node_modules_reactnativedropdownalert_assets_error.png: error: uncompiled PNG file passed as argument. Must be compiled first into .flat file..
error: failed parsing overlays.
:app:processReleaseResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processReleaseResources'.
> Failed to process resources, see aapt output above for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
101 actionable tasks: 2 executed, 99 up-to-date
```

#### Steps to Reproduce / Code Snippets / Usage

Add this lib and try to build a release version of android app with the latest gradle version.

#### Expected Results

Should build and run.

### Additional Information

* React Native version: latest
* react-native-dropdownalert version: latest
* Platform(s) (iOS, Android, or both?): Android
* iOS version: -
* Android version: latest

**Comment by itswaze** [comment] 2018-04-28 15:49
I had the the same problem.
The workaround for now is to add 

> android.enableAapt2=false

to your `android/gradle.properties` file

**Comment by testshallpass** [comment] 2018-05-12 00:04
@dominicrico @itswaze It appears there are several workarounds: https://github.com/facebook/react-native/issues/16906 

I'll look into cleaning it up if I can. What version Android studio, gradle and build tools you guys have?

**Comment by dominicrico** [comment] 2018-05-14 11:46
@testshallpass 

I'm using the latest version of all 3, I think.

Android Studio: 3.1.1
Gradle: 4.3.1
Build Tools:  27.0.3

**Comment by nabeelpkl** [comment] 2018-07-25 15:54
is there a solution for this yet ?

**Comment by vinicarra** [comment] 2018-08-16 19:41
Isn't this fixed yet?

**Comment by r3wt** [comment] 2018-08-25 17:59
solution from another thread:

1. add  `org.gradle.configureondemand=true` to **gradle.properties**
2. stop all gradle daemons `./gradlew --stop`
3. remove build folder and tmp folders
4. `./gradlew assembleRelease`

**Comment by testshallpass** [comment] 2018-09-30 16:49
It's resolved in react-native [0.57.1](https://github.com/facebook/react-native/commit/da6a5e0439c168147271ef66ad5ebbeebd6fce3bl) 

However, I'm looking into supporting a workaround [solution](https://github.com/facebook/react-native/issues/16906#issuecomment-363992890) for those not yet ready to make the jump to that react-native version.

**Comment by testshallpass** [comment] 2018-09-30 17:53
I'm not able to reproduce. I ran `./gradlew assembleRelease` on example project using:

Android Studio: **3.2**
Gradle: **4.6**
Android Plugin: **3.2.0**
Build Tools: **28.0.2**

```shell
> Configure project :app 
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html

> Task :app:bundleReleaseJsAndAssets 
Scanning folders for symlinks in /path/to/react-native-dropdownalert/Example/node_modules (19ms)
Scanning folders for symlinks in /path/to/react-native-dropdownalert/Example/node_modules (28ms)
Loading dependency graph, done.
warning: the transform cache was reset.
bundle: Writing bundle output to: /path/to/react-native-dropdownalert/Example/android/app/build/intermediates/assets/release/index.android.bundle
bundle: Done writing bundle output
bundle: Copying 10 asset files
bundle: Done copying assets

// ... skip showing download
 
BUILD SUCCESSFUL in 3m 2s
28 actionable tasks: 27 executed, 1 up-to-date
```

**Comment by testshallpass** [comment] 2018-11-25 15:08
This is a downstream issue and so will not fix and will not add a workaround to address it.

**Closed by testshallpass** 2018-11-25 15:08 UTC
Labels: android, bug, major

**Comment by AshishSuhane** [comment] 2021-07-20 03:28
> #### Short Description
> Gradle Build fails, because of image sources.
> Gradle Log:
> 
> ```
> :app:processReleaseResources
> /XXX/RNApp/android/app/build/intermediates/res/merged/release/drawable-xhdpi/node_modules_reactnativedropdownalert_assets_error.png: error: uncompiled PNG file passed as argument. Must be compiled first into .flat file..
> error: failed parsing overlays.
> :app:processReleaseResources FAILED
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':app:processReleaseResources'.
> > Failed to process resources, see aapt output above for details.
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 0s
> 101 actionable tasks: 2 executed, 99 up-to-date
> ```
> 
> #### Steps to Reproduce / Code Snippets / Usage
> Add this lib and try to build a release version of android app with the latest gradle version.
> 
> #### Expected Results
> Should build and run.
> 
> ### Additional Information
> * React Native version: latest
> * react-native-dropdownalert version: latest
> * Platform(s) (iOS, Android, or both?): Android
> * iOS version: -
> * Android version: latest

Remove .png images from the code resolved this issue for me. You can use other files like .jpg or .svg  instead of .png for error images or other static assets.
